### ISSUE TITLE
WASM: Sandbox logging optimization

### ISSUE THREAD

**Issue by mandarjog** [envoyproxy/envoy-wasm#109]
`LogDebug(absl::StrCat(x, y, z));`   does not get executed when used directly from envoy because `LogDebug` macro will put a level guard on it.

The same call inside the sandbox needs to cross into the Host and then get dropped.
Consider adding loglevel indicator inside the sandbox so that the Macro in the sandbox is also efficient.

**Comment by jplevyak** [comment]
This is going to require some surgery in envoy.  At the same time we should add an API to allow the log_format ("pattern") to be set on a per logging id, and add an id for wasm_plugin which only logs the records from within the VM and then set that pattern to not log the filename and line number in envoy (since it is always the same).
