### ISSUE TITLE
Dynamic metadata does not behave like expected

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy-wasm#14]
WASM API exposes a read/write operations to exchange data between host and modules using dynamic metadata from Envoy's StreamInfo. Dynamic metadata does not behave like a key-value store, since it uses protobuf merge of JSON structs for values mapping the same key. In particular, it is impossible to delete values set in the dynamic metadata.

**Comment by jplevyak** [comment]
Unfortunately the "setDynamicMetadata" method of StreamInfo does a merge.

In order to not be incompatible with that we have several alternatives:
  - change the API call to be replaceMetadataStruct() which would add or overwrite the Struct().
  - add an API call removeMetadataStruct
  - add an API call removeMetadataValue (orthogonal)

However this begs the question as to why the StreamInfo API is defined that way?  Is the intended usage is as a write-once metadata repository?

**Comment by kyessenov** [comment]
The intended use of the dynamic metadata is storing per-filter metadata (see the various per-filter metadata fields in xDS API). It was not designed to be an arbitrary store of values. Hence, the keys are specified to be the filter unique names, and the values are filter xDS configs.

**Comment by kyessenov** [comment]
If the goal is inter-operability with the rest of envoy filter ecosystem, then we should consider storing the entire value context in a single dynamic metadata object under "envoy.wasm", and then adding APIs to manipulate the value object. If we go this way, we should consider using something else than `protobuf.Struct` as a key value store.

**Comment by jplevyak** [comment]
It seems this is nuanced enough to require a design document with use cases and discussion in the community so that we do not end up thrashing.

**Comment by jplevyak** [comment]
Obsolete.  We now use FilterState.
