### ISSUE TITLE
Set-up CI system

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy-wasm#19]
This repo does not have circle CI system set-up, which I presume requires administrative access to envoyproxy organization. Since the build here is fairly similar to the original envoyproxy repository it forked off from, I think it should be a matter of registering the hooks in github and circle.

@htuch do you think you can help us get the circle CI hooked? If not, can you suggest someone who can help with it. It should be noted that the build is somewhat heavier (~40min build time) since it depends on v8 from chrome.

**Comment by dio** [comment]
I think @lizan can help with this 🙂

**Comment by lizan** [comment]
I don't have enough permission, @mattklein123 or @htuch has.

**Comment by mattklein123** [comment]
We can set this up, but can we potentially strip down the tests/configs we use in the CI config so that we can save some $$$ while iterating?

**Comment by kyessenov** [comment]
@PiotrSikora has been working on bazel configs to strip away WASM VM flavors from the build. Can you help here with a cheaper bazel config? I am not very familiar with how bazel is set up to bring in v8 and others.

**Comment by PiotrSikora** [comment]
@mattklein123 we could run only WASM tests, since we're not touching anything outside of WASM filters, so it's unlikely that anything else is going to be broken. We could also limit configurations to `bazel.release`, `bazel.asan`, and perhaps `bazel.tsan`.

2 caveats:
1. We're still using build recipes, so both V8 & WAVM are always built right now, even once #1 is merged. This will get fixed soon-ish.
2. WAVM is leaking tiny bit of memory due to a few global allocations, so tests for optimized builds and sanitizers are failing right now when built with WAVM.

**Comment by mattklein123** [comment]
@PiotrSikora SGTM. LMK when the CI config is setup and I can flip the switch.

**Comment by PiotrSikora** [comment]
Fixed in #53. Thanks @mattklein123 & @lizan.
