### ISSUE TITLE
Generalize setState to setSelectorExpression

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy-wasm#198]

**Comment by PiotrSikora** [comment]
Nit, but is there any reason why this is called `{set,get}SelectorExpression`? It sounds like an implementation detail. Wouldn't `{set,get}Property` (or even the current `{set,get}State`) be more generic and still accurate?

cc @jplevyak

**Comment by kyessenov** [comment]
I really don't want a naming bike-shed. I think we went through a few iterations, and just settled on getSelectorExpression. Property sounds a bit too web-ish, which is not the intent.

**Comment by jplevyak** [comment]
I don't know.  getProperty and setProperty are shorter and more descriptive.  After all, we are not getting an expression, but rather a value and getSelectorExpressionValue is a mouthful.  Even getExpressionValue is a bit much, particularly since are not actually doing full expression evaluation AFAICT.  Oh and getSelectorValue is right out.  What is a selector anyway, and getValue is too broad.

**Comment by kyessenov** [comment]
That's fine with me. Is everyone on-board to rename then?

**Comment by PiotrSikora** [comment]
Sounds like it.
