### ISSUE TITLE
"examples.wasm"  failure

### ISSUE THREAD

**Issue by gektorbr** [envoyproxy/envoy-wasm#353]
*Title*: *`examples.wasm` doesn't work*

*Description*:
I've tried to run `examples.wasm` demo using docker (as described here: https://github.com/envoyproxy/envoy-wasm/tree/master/examples/wasm#quick-start). It fails and the log says:

```
proxy_1        | [2019-12-25 23:01:06.481][6][critical][main] [source/server/server.cc:95] error initializing configuration '/etc/envoy.yaml': Didn't find a registered implementation for name: 'envoy.filters.http.wasm'
```

**Comment by pawalt** [comment]
I ran into this as well. The example uses the default envoy image, but that won't work until envoy-wasm is actually merged into envoy. For now, you have to build envoy-wasm locally and drop it into the envoy container by uncommenting line 13 of the docker compose file.
I ran this command to build with wasm support:

```
./ci/run_envoy_docker.sh "BAZEL_BUILD_EXTRA_OPTIONS='--define wasm=enabled' ./ci/do_ci.sh bazel.dev.notest"
```

I also defined an a build option `bazel.dev.notest` that is the same is `bazel.dev` but doesn't run any tests since the WAVM build isn't working with testing right now.

**Comment by Rajith90** [comment]
Isn't this still not supported in latest envoy version

**Comment by caroldesenne** [comment]
@pawalt  It seems that this target **bazel.dev.notest** is not supported anymore

**Comment by jplevyak** [comment]
This depends on upstreaming which we are actively trying to do.

**Comment by bochuxt** [comment]
sudo ./ci/run_envoy_docker.sh "BAZEL_BUILD_EXTRA_OPTIONS='--define wasm=enabled' ./ci/do_ci.sh bazel.release"
