### ISSUE TITLE
Throwing exception in wasm module won't work

### ISSUE THREAD

**Issue by bianpengyuan** [envoyproxy/envoy-wasm#9]
Throw exception like [this](https://github.com/envoyproxy/envoy-wasm/blob/master/api/wasm/cpp/proxy_wasm_impl.h#L1120) won't work because it triggers cxa_allocate_exception which is not well implemented.

@jplevyak @PiotrSikora

**Comment by jplevyak** [comment]
It seems that exception support in emscripten is... poor. First, in order to get exception support we need to add "-s DISABLE_EXCEPTION_CATCHING=0" to the Makefile.

After that, we would need a great deal of support, implementing a raft of invoke_XXX and dynCall_XXX functions in addition to __cxa calls.

All this is likely to change as well when we move to the new upstream (LLVM) based backend for emscripten.

**Comment by jplevyak** [comment]
https://github.com/envoyproxy/envoy-wasm/pull/72

**Comment by jplevyak** [comment]
https://github.com/jplevyak/envoy-wasm/tree/wasm-exceptions
