### ISSUE TITLE
WASM: Add additional request bound information 

### ISSUE THREAD

**Issue by mandarjog** [envoyproxy/envoy-wasm#97]
We need access to the following fields from stream_info

1. requestComplete()
2. startTime()
3. bytesSent(), bytesReceived()
4. protocol()
5. responseCode()
6. downstreamSslConnection()->peerCertificatePresented()
 7. downstreamSslConnection()->tlsVersion()

The following are not available in envoy.
upstreamSslConnection()->*

**Comment by mandarjog** [comment]
@jplevyak @kyessenov

**Comment by bianpengyuan** [comment]
I think we'd also like source ip/port and destination ip.

**Comment by kyessenov** [comment]
I'm going to express these in CEL attribute context. The connection stuff will need to change, I think since the legacy `connection` did not handle upstream/downstream distinction well. If we could get inbound/outbound native in envoy, we could re-introduce source/destination stuff.

I can take on upstreamSslConnection, too -- that seems like a general blocker for any upstream TLS telemetry.

**Comment by jplevyak** [comment]
https://github.com/envoyproxy/envoy-wasm/pull/113

**Comment by mandarjog** [comment]
@jplevyak it seems that `downstreamSslConnection()->peerCertificatePresented()` is not available in the API, (or I could not find it)

**Comment by kyessenov** [comment]
I think this is all available, re-open if missing.
